# Electromagnetics

This porject define methods for generate aproximate
solutions to Electrostatics and Magnetostatics
Vizualize electric Fields in a clear way aim to
graphically explore the properties of the maxwell equations

## Features

### Electrostatics

### Magnetostatics

### Electro Motive Force
